"""
Dynamic resource discovery interface.

This module will eventually connect to dataset/model registries
such as Hugging Face, OpenML, torchvision, scikit-learn, etc.

The rest of Cognilab should not care where a resource came from.
"""


def discover_resources(experiment: dict) -> dict:
    """
    Discover datasets, models and tools suitable for an experiment.

    Parameters
    ----------
    experiment:
        Generic experiment requirements generated by the
        Hypothesis Agent.

    Returns
    -------
    dict
        Candidate resources for the Experiment Agent.
    """

    dataset_requirements = experiment.get(
        "dataset_requirements",
        {}
    )

    model_requirements = experiment.get(
        "model_requirements",
        {}
    )

    return {
        "datasets": [],
        "models": [],
        "tools": [],
        "requirements": {
            "dataset": dataset_requirements,
            "model": model_requirements
        }
    }